AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chirashi Kitchen API

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 512
    Environment:
      Variables:
        # DynamoDB Tables
        ARTICLES_TABLE_NAME: !Ref ArticlesTable
        COMPANIES_TABLE_NAME: !Ref CompaniesTable
        STORES_TABLE_NAME: !Ref StoresTable
        FLYERS_TABLE_NAME: !Ref FlyersTable
        ADMINS_TABLE_NAME: !Ref AdminsTable
        USERS_TABLE_NAME: !Ref UsersTable
        FAVORITE_STORES_TABLE_NAME: !Ref FavoriteStoresTable
        RECIPES_TABLE_NAME: !Ref RecipesTable
        SHARED_RECIPES_TABLE_NAME: !Ref SharedRecipesTable
        # S3
        S3_BUCKET_NAME: !Ref ImagesBucket
        # JWT
        JWT_SECRET_KEY: !Ref JWTSecretKey
        # AWS
        AWS_REGION: !Ref AWS::Region
        LOG_LEVEL: INFO
        ENVIRONMENT: !Ref Environment
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  JWTSecretKey:
    Type: String
    NoEcho: true
    Description: JWT secret key for token generation

Resources:
  # API Gateway
  ChirashiKitchenApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # ==================== 管理者API ====================

  # 認証
  AdminLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: admin.handlers.auth.admin_login
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AdminsTable
        - DynamoDBWritePolicy:
            TableName: !Ref AdminsTable
      Events:
        AdminLogin:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/auth/login
            Method: post

  # コラム管理API（統合版 - コールドスタート対策）
  ArticlesApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: admin.handlers.articles_router.route_articles
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Events:
        ArticlesList:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/articles/list
            Method: get
        ArticleGet:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/articles/list/{articleId}
            Method: get
        ArticleCreate:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/articles/add
            Method: post
        ArticleUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/articles/update/{articleId}
            Method: put
        ArticleDelete:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/articles/delete/{articleId}
            Method: delete
        ArticleBulkStatus:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/articles/bulk-status
            Method: put
        ArticleBulkDelete:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/articles/bulk-delete
            Method: delete

  # アカウント管理API（統合版 - コールドスタート対策）
  AccountsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: admin.handlers.accounts_router.route_accounts
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AdminsTable
      Events:
        AccountsList:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/accounts/list
            Method: get
        AccountGet:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/accounts/list/{accountId}
            Method: get
        AccountCreate:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/accounts/add
            Method: post
        AccountUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/accounts/update/{accountId}
            Method: put
        AccountDelete:
          Type: Api
          Properties:
            RestApiId: !Ref ChirashiKitchenApi
            Path: /admin/accounts/delete/{accountId}
            Method: delete

  # ==================== DynamoDB Tables ====================

  # 管理者
  AdminsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: admins
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: adminId
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: role
          AttributeType: S
      KeySchema:
        - AttributeName: adminId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: CompanyIndex
          KeySchema:
            - AttributeName: companyId
              KeyType: HASH
            - AttributeName: role
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # コラム
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: articles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: articleId
          AttributeType: N
        - AttributeName: status
          AttributeType: S
        - AttributeName: publishedAt
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: articleId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: publishedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: publishedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # 企業
  CompaniesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: companies
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: contractStatus
          AttributeType: S
        - AttributeName: contractPlan
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ContractStatusIndex
          KeySchema:
            - AttributeName: contractStatus
              KeyType: HASH
            - AttributeName: contractPlan
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # 店舗
  StoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: stores
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: storeId
          AttributeType: S
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: prefecture
          AttributeType: S
        - AttributeName: region
          AttributeType: S
      KeySchema:
        - AttributeName: storeId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CompanyIndex
          KeySchema:
            - AttributeName: companyId
              KeyType: HASH
            - AttributeName: storeId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: RegionIndex
          KeySchema:
            - AttributeName: prefecture
              KeyType: HASH
            - AttributeName: region
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # チラシ
  FlyersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flyers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: flyerId
          AttributeType: S
        - AttributeName: storeId
          AttributeType: S
        - AttributeName: validFrom
          AttributeType: S
        - AttributeName: prefecture
          AttributeType: S
        - AttributeName: companyId
          AttributeType: S
      KeySchema:
        - AttributeName: flyerId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: StoreIndex
          KeySchema:
            - AttributeName: storeId
              KeyType: HASH
            - AttributeName: validFrom
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: RegionIndex
          KeySchema:
            - AttributeName: prefecture
              KeyType: HASH
            - AttributeName: validFrom
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: CompanyIndex
          KeySchema:
            - AttributeName: companyId
              KeyType: HASH
            - AttributeName: validFrom
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ユーザー
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # お気に入り店舗
  FavoriteStoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: favorite-stores
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: storeId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: storeId
          KeyType: RANGE

  # AIレシピ（キャッシュ）
  RecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: recipes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: flyerId
          AttributeType: S
      KeySchema:
        - AttributeName: flyerId
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl

  # 共有レシピ
  SharedRecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: shared-recipes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sharedRecipeId
          AttributeType: S
        - AttributeName: flyerId
          AttributeType: S
        - AttributeName: sharedAt
          AttributeType: S
      KeySchema:
        - AttributeName: sharedRecipeId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: FlyerIndex
          KeySchema:
            - AttributeName: flyerId
              KeyType: HASH
            - AttributeName: sharedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # S3 Bucket
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub chirashi-kitchen-images-${Environment}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            MaxAge: 3000

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ChirashiKitchenApi}.execute-api.${AWS::Region}.amazonaws.com/v1"

  AdminsTableName:
    Description: "Admins DynamoDB table name"
    Value: !Ref AdminsTable

  ArticlesTableName:
    Description: "Articles DynamoDB table name"
    Value: !Ref ArticlesTable

  ImagesBucketName:
    Description: "S3 Images bucket name"
    Value: !Ref ImagesBucket
